// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo73JG7xu3bDk06syU_f0XaMZPYe-fYs0',
    appId: '1:605113925498:android:6b439868270772481b20c3',
    messagingSenderId: '605113925498',
    projectId: 'mizamapp',
    storageBucket: 'mizamapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_QXGG9kkRJNg62Cv-0iIutdSnN8Nw_E',
    appId: '1:605113925498:ios:f6811c8bcf61777a1b20c3',
    messagingSenderId: '605113925498',
    projectId: 'mizamapp',
    storageBucket: 'mizamapp.appspot.com',
    androidClientId: '605113925498-d7749uvl1qqv0c5r5p7eu32kasf4qfnk.apps.googleusercontent.com',
    iosClientId: '605113925498-1vegcliu5hk6jdttt4litt3789e5ljof.apps.googleusercontent.com',
    iosBundleId: 'com.example.mizamApp',
  );
}
